### ISSUE TITLE
Miss calculation result in function CalculateUptimeAvailability()

### ISSUE THREAD

**Issue by ganiamri** [haidlir/golang-uptime-sla-calculator#5]
Halo Mas Naqvi,

I found miss calculation result in function CalculateUptimeAvailability() with this set of uptime data.
|Unixtime     | Uptime     | Delta Unixtime     |  Delta Uptime  | 
| ------------------- | --------------  | ----------- |  -----------  |
| 1630741500 | 31541552 | 0            | 0       |
| 1630741800 | 31541852 | 300       |  300      |
| 1630742100 | 31542152 | 300       | 300     |
| 1630742400 | 31542457 | 300       | 305*     |
| 1630742700 | 31542752 | 300       | 295*      |

Using this data will output `0.75` while i think it supposed to return `1.00` uptime availability .

So far, i suspect the `transformToSpreadedUptime` function need to be reviewed. CMIIW

Thanks.

**Comment by haidlir** [comment]
Thanks Mas @ganiamri ,
After tracing the codes, I think the reason why unixtime 1630742700 not included in the uptime calculation is its delta uptime is less than delta unixtime. I'm curious, what if we add some tolerance such as 0.9 * deltatimestamp in this part. Will it accomodate your need ? Can you try it in your local first ?
https://github.com/haidlir/golang-uptime-sla-calculator/blob/7dd5e6766d524212a2230a1aa451e03149f65e63/sla-calculator/sla_calculator.go#L149

**Comment by haidlir** [comment]
No further discussion
